CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password TEXT NOT NULL,
    account_type VARCHAR(50) NOT NULL,
    datetime_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    request_name VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    model_type VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS battery_data (
    data_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES requests(request_id) ON DELETE CASCADE,
    cycle_number INT NOT NULL,
    point_index INT NOT NULL,
    voltage_in_v DOUBLE PRECISION NOT NULL,
    current_in_a DOUBLE PRECISION NOT NULL,
    charge_capacity_in_ah DOUBLE PRECISION NOT NULL,
    discharge_capacity_in_ah DOUBLE PRECISION NOT NULL,
    nominal_capacity_in_ah DOUBLE PRECISION NOT NULL,
    time_in_s DOUBLE PRECISION NOT NULL,
    temperature_in_c DOUBLE PRECISION,
    form_factor VARCHAR(355)
);

CREATE TABLE IF NOT EXISTS prediction_response_rul (
    response_rul_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES requests(request_id) ON DELETE CASCADE,
    status VARCHAR(200) NOT NULL,
    error VARCHAR(200),
    predicted_rul DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS prediction_response_soh (
    response_soh_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES requests(request_id) ON DELETE CASCADE,
    status VARCHAR(200) NOT NULL,
    error VARCHAR(200),
    predicted_soh DOUBLE PRECISION,
    target_cycle INT
);

CREATE TABLE IF NOT EXISTS recommendation_response (
    recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES requests(request_id) ON DELETE CASCADE,
    status VARCHAR(300) NOT NULL,
    message VARCHAR(300),
    target_energy_wh DOUBLE PRECISION,
    nominal_voltage_in_v DOUBLE PRECISION,
    error VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS recommendation_profile (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL REFERENCES recommendation_response(recommendation_id) ON DELETE CASCADE,
    profile_type VARCHAR(100) NOT NULL,
    charge_c_rate DOUBLE PRECISION NOT NULL,
    discharge_c_rate DOUBLE PRECISION NOT NULL,
    soc_min DOUBLE PRECISION NOT NULL,
    soc_max DOUBLE PRECISION NOT NULL,
    dod DOUBLE PRECISION NOT NULL,
    ambient_temp_proxy DOUBLE PRECISION NOT NULL,
    nominal_voltage_v DOUBLE PRECISION NOT NULL,
    predicted_degradation_rate DOUBLE PRECISION NOT NULL,
    charge_time_sec DOUBLE PRECISION NOT NULL,
    delivered_energy_wh DOUBLE PRECISION NOT NULL,
    thermal_risk DOUBLE PRECISION NOT NULL
);
