CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password TEXT NOT NULL,
    account_type VARCHAR(50) NOT NULL,
    datetime_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    request_name VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS battery_data (
    data_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES requests(request_id) ON DELETE CASCADE,
    cycle_number INT NOT NULL,
    point_index INT NOT NULL,
    voltage_in_v DOUBLE PRECISION NOT NULL,
    current_in_a DOUBLE PRECISION NOT NULL,
    charge_capacity_in_ah DOUBLE PRECISION NOT NULL,
    discharge_capacity_in_ah DOUBLE PRECISION NOT NULL,
    nominal_capacity_in_ah DOUBLE PRECISION NOT NULL,
    soc_start DOUBLE PRECISION NOT NULL,
    soc_end DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS prediction_response (
    response_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES requests(request_id) ON DELETE CASCADE,
    status VARCHAR(200) NOT NULL,
    error VARCHAR(200),
    predicted_soh DOUBLE PRECISION,
    predicted_soh_percent DOUBLE PRECISION,
    target_cycle DOUBLE PRECISION
);
